import type { Metadata } from 'next';
import { ReactNode } from 'react';

import '@/styles/globals.css';

import Gnb from '@/components/common/Gnb/Gnb';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="ko" className="antialiased">
      <body>
        <Gnb />
        <main>{children}</main>
      </body>
    </html>
  );
}
