import type { Metadata } from 'next';
import { ReactNode } from 'react';

import '@/styles/globals.css';

import QueryProvider from '@/components/common/QueryProvider';
import ToastContainer from '@/components/common/toast/ToastContainer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="ko" className="antialiased">
      <body className="bg-[#f2ebdc]">
        <QueryProvider>{children}</QueryProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
